# .readthedocs.yaml

# Required: The version of Python to use for building your documentation
python:
  version: 3.8  # Adjust the version as needed

# Required: Specify your project's documentation type
documentation_type: sphinx

# Optional: Set the Sphinx builder to HTML (default is 'html')
build:
  image: latest  # You can specify a specific Docker image if needed
  format: html

# Required: Specify the Sphinx configuration file (conf.py) location
sphinx:
  configuration: docs/source/conf.py  # Update with your actual path

# Optional: Specify additional dependencies needed for building your documentation
# For Django, you may need to install dependencies like sphinxcontrib-django
requirements_file: docs/requirements.txt  # Update with your actual path

# Optional: Specify the Python environment for building documentation
# python:
#   version: 3.8
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - -r docs/requirements.txt

# Optional: Specify the version of Sphinx to use (default is the latest)
# build:
#   image: latest
#   format: html
#   fail_on_warning: true

# Optional: Specify custom builds or configurations
# build:
#   image: latest
#   format: html
#   fail_on_warnings: true
#   fail_on_mdchecks: true
#   config: docs/sphinx.conf.py
#   builds:
#     - image: latest
#       format: pdf

# Optional: Specify custom Python versions for your project
# python:
#   version: 3.8
#   setup_py_install: true

# Optional: Set environment variables if needed
# environment:
#   DJANGO_SETTINGS_MODULE: myproject.settings

# Optional: Specify advanced build settings
# build:
#   image: latest
#   format: html
#   config: docs/sphinx.conf.py
#   fail_on_warnings: true
#   fail_on_mdchecks: true
#   builder: dirhtml
#   output_dir: docs/build/html

# Optional: Specify custom pre and post build commands
# before:
#   - echo "Running before build..."
# after:
#   - echo "Running after build..."
