# Generated by Django 4.2.4 on 2023-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categoryimgs', verbose_name='Category Image')),
            ],
        ),
    ]
