# Generated by Django 4.2.4 on 2023-08-30 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuskcourses', '0002_delete_coursecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course_image', models.ImageField(blank=True, default='courseimgs/70-702065_django-python-logo-apress-the-definitive-guide-to_T18MEpY.png', null=True, upload_to='courseimgs', verbose_name='Course Image')),
                ('certificate', models.ImageField(blank=True, default='certimgs/Navy_and_Gold_Geometric_Luxury_Modern_Certificate.png', null=True, upload_to='certimgs', verbose_name='Certificate Image')),
                ('duration', models.DurationField(default=datetime.timedelta(days=84))),
                ('activation_status', models.BooleanField(default=False)),
                ('recurring_payment', models.BooleanField(default=False)),
                ('onetime_payment', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_image', models.ImageField(blank=True, default='categoryimgs/original-9cc30d293a2efd79103e7add6d16b0be.png', null=True, upload_to='categoryimgs', verbose_name='Category Image')),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_module_image', models.ImageField(blank=True, default='courseimgs/70-702065_django-python-logo-apress-the-definitive-guide-to_T18MEpY.png', null=True, upload_to='courseimgs', verbose_name='Course Module Image')),
                ('activation_status', models.BooleanField(default=False)),
                ('course_video', models.FileField(default='coursevids/original-cc0696de49d294a0c72f89b52e5cf52a.mp4', upload_to='coursevids')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.course')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='CourseSubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('course_video', models.FileField(default='coursevids/original-cc0696de49d294a0c72f89b52e5cf52a.mp4', upload_to='coursevids')),
                ('course_image', models.ImageField(blank=True, default='courseimgs/70-702065_django-python-logo-apress-the-definitive-guide-to_T18MEpY.png', null=True, upload_to='courseimgs', verbose_name='Course SubModule Image')),
                ('activation_status', models.BooleanField(default=False)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.coursemodule')),
            ],
            options={
                'verbose_name_plural': 'Sub Modules',
            },
        ),
        migrations.CreateModel(
            name='CourseSubModuleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('course_sub_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.coursesubmodule')),
            ],
            options={
                'verbose_name_plural': 'Sub Module Quizzes',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], default='Stripe', max_length=50)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='CourseUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='tuskcourses.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Users',
            },
        ),
        migrations.CreateModel(
            name='CourseSubModuleQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('correct_status', models.BooleanField(default=False)),
                ('sub_module_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.coursesubmodulequiz')),
            ],
            options={
                'verbose_name_plural': 'Sub Module Quiz Answers',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reviewmsg', models.TextField(default='A very nice course')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.course')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Reviews',
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.course')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.paymentgateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModuleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='_')),
                ('course_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.coursemodule')),
            ],
            options={
                'verbose_name_plural': 'Module Quizzes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='courses', to='tuskcourses.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
