# Generated by Django 4.2.4 on 2023-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModuleQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('correct_status', models.BooleanField(default=False)),
                ('module_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuskcourses.coursemodulequiz')),
            ],
            options={
                'verbose_name_plural': 'Module Quiz Answers',
            },
        ),
    ]
