# Generated by Django 4.2.4 on 2023-08-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0004_coursemodulequizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish')], default='English', max_length=50),
        ),
    ]
