# Generated by Django 4.2.4 on 2023-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0005_course_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
    ]
