# Generated by Django 4.2.4 on 2023-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0006_language_remove_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='related_languages', to='tuskcourses.language'),
        ),
    ]
