# Generated by Django 4.2.4 on 2023-09-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0008_paymentmethod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
