# Generated by Django 4.2.4 on 2023-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0009_course_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(auto_created=True, max_length=256, null=True),
        ),
    ]
