# Generated by Django 4.2.4 on 2023-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuskcourses', '0010_alter_course_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
