# Generated by Django 4.2.4 on 2023-09-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuskcourses", "0013_course_stripe_price_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseusers",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="courseusers",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="course",
            name="stripe_product_id",
        ),
        migrations.DeleteModel(
            name="CoursePayment",
        ),
        migrations.DeleteModel(
            name="CourseUsers",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentGateway",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
