# Generated by Django 4.2.4 on 2023-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuskcourses", "0015_course_strip_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="strip_id",
            field=models.CharField(auto_created=True, max_length=255, null=True),
        ),
    ]
