# Generated by Django 4.2.4 on 2023-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuskcourses", "0018_alter_course_strip_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="strip_id",
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
