# Generated by Django 4.2.4 on 2023-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuskcourses", "0019_remove_course_strip_id_course_stripe_price_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
